### ISSUE TITLE
There is no deployment on GitHub

### ISSUE THREAD

**Issue by AlexErdei73** [Houser97/Blog-API#1]
I have seen the deployed version from The Odin Project and it's working. It also sorts out the problem with Heroku. I think you should include it here and maybe a whole description in the README.md file of how you did it. That would be helpful for fellow TOP learners, like me regarding how we should replace Heroku on less important projects, which we just do not want to pay the 7$ per app price.
The app looks great, it's a shame, that we can't create an account to put real blogs there or even just comment on your ones. It would have been great to see some real blog posts too. It can be for example about the deployment, and how you replaced Heroku in this case. It's just an idea of course. The app looks and works very nice, so I liked it on TOP and you have a star too:)

**Comment by Houser97** [comment]
Hi! I'm glad you liked the project :).
Thanks for the feedback, I'll look into those issues about not being able to comment on posts and creating accounts.

I will start creating the README file elaborating on the solution about Heroku that I employed and hopefully it will be ready by today.

**Comment by AlexErdei73** [comment]
I think the biggest issue is that the link to the deployed app is not available on the GitHub page. Think of an expert, who wants to try the app, but he can't because the link is not available here on GitHub. The other things are just suggestions, how you could put there some nice content. They could not only see how nice the app is but even some interesting blog posts too. If you made the registration and posting available to the public, maybe someone else put their post here too. In that case, you need to keep an eye on the app, so maybe it's not worth it, but the other things would be good in my opinion.

**Comment by Houser97** [comment]
I have added the README file and explained the steps I took to host my app in Render. I also added the link to the deployed app in that file. You can reach me out if something is not clear in the steps I mentioned. 

I will also start making the README files for my other projects. Thanks for the suggestions!

**Comment by AlexErdei73** [comment]
You can close this issue as you posted the deployed site as well. Now everybody can see the working website from your GitHub, which is part of your portfolio. Congratulations again, it's very nice work. Think of creating a real blog post with it, at least one. Maybe later, when you have time, you can let us create blog posts as well. If you write down the problem with Heroku and your specific detailed solution, it can be a great blog post. I know it's difficult and I don't like writing a thing like this, but in the case of this app, it can be a good idea. It shows you from a different side, not just like a great programmer, but someone who can write about it well. It's certainly advantageous. Blog posts are a tiny bit more difficult than simple messages and these can contain code blocks too. You should think of web security regarding them. I think we can learn from this a lot. I am curious if I could make something nice like your solution. Well done, it just looks very nice:)

**Comment by AlexErdei73** [comment]
Thank you for the detailed description of the deployment. This is equivalent service to the old Heroku when it was free. This can certainly be your own blog and it can be very helpful to others too. Congratulations! The README.md file has become much more informative, I think it will help you on your job hunting journey if you want to do that.
