### ISSUE TITLE
Same Origin Policy has been disabled by CORS, although you serve front end code from same origin

### ISSUE THREAD

**Issue by AlexErdei73** [Houser97/Blog-API#2]
From the code and README.md file, it seems that you serve the front-end code from the same origin as your back-end code. As far as I know in this case you should not apply CORS as your app works under the same origin policy, which is the cornerstone of the security of your API. As far as I understand the removal of the CORS middleware would make your API much more secure as it would enforce the same origin policy.

**Comment by Houser97** [comment]
Hi, you are right about it! I completely forgot to remove that section as I was deploying the server and client separately at first. Tomorrow I'll remove it and after finishing some projects I'll also start thinking about writing that post about deploying in Render (:

**Comment by AlexErdei73** [comment]
I am happy that I could have helped to spot it. Security should be always first priority, especially in back-end-focused apps like this. The rest is not compulsory according to the original project description at all. It is just my personal opinion that it can come out very positive when you are using your projects in job hunting. It is not necessary of course.

**Comment by Houser97** [comment]
I have removed CORS from this project, and also it helped to prevent me from making the same mistake in a different project. On the other side, I am actually thinking about using some projects in job hunting so it will come in handy to add some value as you suggest, thank you!

**Comment by AlexErdei73** [comment]
I hope it helps. I used to work in marketing, even if it was not online marketing. Valuable content in your portfolio projects can help introduce you to a better and more engaging way. Even TOP is mainly popular because of its content, not its look. The look is crucial when the targeted position is front-end focused, but the content can also help, so better not to neglect it starting from the README.md file and all that you present through your apps. As I see the market we will need all the tricks we can do:)

**Comment by Houser97** [comment]
It certainly helps!
I hadn't paid enough attention to the README.md file until just when I wrote the deployment steps in Render, and now I see the role it plays. I appreciate you sharing your experience with me, I'll start working on some aspects that I've been neglecting regarding what you say (:
